# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 1
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - no-stale
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale and it will be closed soon.
  This mechanism helps to prioritize feature requests which received more support from the community.
  If you want to open again this feature you have to provide a Pull Request.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: true
