
connectors:
  - file: connectorTest
    name: tes
    params:
      testType: withdrawal
  - file: connectorRIS
    name: ris
    params:
      url: wss://ris-live.ripe.net/v1/ws/
      moreSpecific: true
      type: UPDATE
      host: rrc00
      socketOptions:
        includeRaw: false

monitors:
  - file: monitorHijack
    channel: hijack
    name: basic-hijack-detection
  - file: monitorNewPrefix
    channel: newprefix
    name: prefix-detection
  - file: monitorVisibility
    channel: visibility
    name: withdrawal-detection

reports:
  - file: reportFile
    channels:
      - hijack
      - newprefix
      - visibility
  - file: ReportEmail
    channels:
      - hijack
      - newprefix
      - visibility
    params:
      smtp: smtp.gmail.com
      email: sender@email
      port: 465
      secure: true
      user: user
      password: password
      notifiedEmails:
        default:
          - me1@email.it
          - me2@email.it

checkStaleNotificationsSeconds: 30
notificationIntervalSeconds: 10
clearNotificationQueueAfterSeconds: 10 # If nothing happened in the meanwhile

# The file containing the monitored prefixes. Please see monitored_prefixes_test.yml for an example
# This is an array (use new lines and dashes!)
monitoredPrefixesFiles:
  - prefixes.yml

logging:
  logRotatePattern: YYYY-MM-DD  # Whenever the pattern changes, a new file is created and the old one rotated
  zippedArchive: true
  maxSize: 20m
  maxFiles: 14d
