# Please, rename this file to config.yml

testMode: true,

checkStaleNotificationsSeconds: 30
notificationIntervalSeconds: 10
clearNotificationQueueAfterSeconds: 10 # If nothing happened in the meanwhile

bufferSize: 10

wsParams:
  moreSpecific: true
  type: "UPDATE"
  host: "rrc21"
  socketOptions:
    includeRaw: false

# The streaming services used to have real-time data
# This is an array (use new lines and dashes!)
websocketDataService: wss://ris-live.ripe.net/v1/ws/

# The file containing the monitored prefixes. Please see monitored_prefixes_test.yml for an example
# This is an array (use new lines and dashes!)
monitoredPrefixesFiles:
  - prefixes.yml


emailConfig:
  enabled: false
  smtp: smtp.gmail.com
  email:
  port: 465
  secure: true
  user:
  password:

notifiedEmails:
  - me@email.it

