on:
  push:
    tags:
      - 'v*'

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          extra-build-deps: git
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            LICENSE
            bin/*
            debian/artifacts/*.deb
